version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 2
    labels:
      - dependencies
      - ci
  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: daily
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 2
    labels:
      - dependencies
      - devcontainer
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 2
    labels:
      - dependencies
      - docker
