networks:
  guacamole_net:
    driver: bridge
    driver_opts:
      com.docer.network.bridge.name: guac_bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
        # gateway is then 172.18.0.1 by convention

services:
  guacamole:
    container_name: guacamole_container
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: WillNotBeUsed
      GUACAMOLE_HOME: /var/tmp/config_dir
    volumes:
      - ./${GUAC_SUBFOLDER-}:/var/tmp/config_dir
    image: guacamole/guacamole:1.6.0
    networks:
      guacamole_net:
        ipv4_address: 172.18.0.4
    ports:
      - "8080/tcp"
    restart: always

  mumble:
    build:
      context: ..              # Projektwurzel, enthält dein Dockerfile
      dockerfile: Dockerfile   # relativ zum context
      target: dev              # entspricht deinem Multi-Stage-Target
    user: node
    init: true                 # ersetzt --init
    working_dir: /home/node
    volumes:
      - ..:/home/node:cached   # entspricht workspaceMount + consistency=cached
    networks:
      guacamole_net:
        ipv4_address: 172.18.0.6
    container_name: mumble_web_container
    ports:
      - "8081:8081"
    depends_on:
      - murmur
    environment:
      - MUMBLE_SERVER=murmur:${MURMUR_PORT:-64738}
      - GUACPWD=${MURMUR_PASSWORD-}
      - SKIP_PREPARE=1

  nginx:
    container_name: nginx_container
    restart: always
    image: nginx
    environment:
      - SSL_DOMAIN=${SSL_DOMAIN:-localhost}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/conf.d/options-ssl-nginx.conf:/etc/nginx/conf.d/options-ssl-nginx.conf:ro
      - ./letsencrypt:/etc/letsencrypt:ro
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - guacamole
      - mumble
    networks:
      guacamole_net:
        ipv4_address: 172.18.0.7
    extra_hosts:
      - "gateway:172.18.0.1"
    command: /bin/bash -c "nginx -g 'daemon off;'"

  murmur:
    image: goofball222/murmur
    networks:
      guacamole_net:
        ipv4_address: 172.18.0.5
    container_name: murmur
    ports:
      - "${MURMUR_PORT:-64738}:${MURMUR_PORT:-64738}"
      - "${MURMUR_PORT:-64738}:${MURMUR_PORT:-64738}/udp"
    volumes:
      - ./murmur_config:/opt/murmur/config
      - ./murmur_data:/opt/murmur/data
      - ./murmur_log:/opt/murmur/log
      - ./letsencrypt:/opt/murmur/cert
    environment:
      - TZ=UTC
